### ISSUE TITLE
Fn::FindInMap not working correctly

### ISSUE THREAD

**Issue by shaicoleman** [bazaarvoice/cloudformation-ruby-dsl#19]
When I convert this JSON and expand it back
http://us-east-1-aws-training.s3.amazonaws.com/self-paced-lab-14/Template1.json

The Fn::FindInMap is lost from the JSON output, and it instead it hardcodes into the JSON the first element of the mapping.

**Comment by SydOps** [comment]
Not really agree the decision to resolves the mapping directly. It increase the maintenance that we need look into the codes to find out which part need be updated.  

Second, it makes the expand json different with original one.
