### ISSUE TITLE
cfn-validate-template not working

### ISSUE THREAD

**Issue by klsetzer** [bazaarvoice/cloudformation-ruby-dsl#25]
Using 0.4.7, I get the following error.  I have AWS_ACCESS_KEY and AWS_SECRETY_KEY set and exported.

$ ./demo.rb cfn-validate-template                                                                                                               cfn-validate-template:  Malformed input-No Credentials were provided - cannot access the service
Usage:
cfn-validate-template
       [--template-file  value ] [--template-url  value ]  [General Options]
For more information and a full list of options, run "cfn-validate-template --help"

Execution of 'cfn-cmd' failed.  To facilitate debugging, the generated JSON template file was not deleted.  You may delete the file manually if it isn't needed: /Users/ksetzer/Projects/outbreak/templates/demo.rb.expanded.json

**Comment by jonaf** [comment]
@klsetzer @aboutte is correct. In general, when you get this error message, it is coming directly from `cfn-cmd` and you can expect the resolution to be the same as if you were not using the cloudformation ruby dsl.
