### ISSUE TITLE
Add default CAPABILITY_IAM capability

### ISSUE THREAD

**Issue by csgyuricza** [bazaarvoice/cloudformation-ruby-dsl#26]
The --capabilities parameter now requires the CAPABILITY_IAM value for cfn-create-stack and cfn-update-stack otherwise the command fails with error ```Malformed input-Requires capabilities : [CAPABILITY_IAM]```

**Comment by csgyuricza** [comment]
Can someone mark this issue as resolved, pls?

**Comment by jonaf** [comment]
Thanks, @csgyuricza !
