### ISSUE TITLE
How do I put a backslash in interpolate?

### ISSUE THREAD

**Issue by pong-takepart** [bazaarvoice/cloudformation-ruby-dsl#29]
Hello,

I am using
```
:UserData => base64(interpolate(my_content))
```

```mycontent``` returns a cloud-init yaml. One of them is this:
```
runcmd:
  - hostname $(curl -s http://169.254.169.254/latest/meta-data/instance-id/ | sed -r -e "s/i-([0-9a-f]{,8})/#{env.downcase}-#{purpose.downcase}-\1-ops.example.com/g")
```

The ```\1``` in the sed command, ```interpolate``` turns it into a ```\u000``` which Cloudformation dislikes.

I'm tryiing to make my system's hostname to be:
from
```
i-abcd1234
```
to this
```
dev-php-abcd1234.ops.example.com
```

Using a regex backreference is not my first choice, but it appears this is the only thing available to me. I'm open to doing it another way as long as I achieve the name. Thank you.

**Comment by temujin9** [comment]
Okay, I can replicate this from irb. It doesn't seem a correct response; let me look closer.

In the mean time: do you actually need interpolate here? It only exists to add in `{{ }}` encased statements from the enclosing template, and I don't see you doing that.

**Comment by temujin9** [comment]
On further examination: a `\1` is interpreted as "octal 1" by Ruby itself. To achieve what you want in a string, use `"\\1"` or `'\1'`.

**Comment by temujin9** [comment]
(http://en.wikibooks.org/wiki/Ruby_Programming/Syntax/Literals#Backslash_Notation for further reference.)
