### ISSUE TITLE
Upload to S3 first to deal with 50k size limit of templates.

### ISSUE THREAD

**Issue by mhalligan** [bazaarvoice/cloudformation-ruby-dsl#30]
cloudformation-ruby becomes unfunctional the moment your expanded template hits 50KB because of the maximum payload of a CLI based body. Uploading to S3 and passing that as the template-url would increase the size by 10x.

**Comment by temujin9** [comment]
@mhalligan Why did you close this?

**Comment by rhenning** [comment]
I'd like to see this feature as well but what would the workflow look like? Upload to S3 bucket of user's choice? Create a randomly-named bucket and key, apply the change, and destroy when complete?  IIRC there's a s3 bucket that is created dynamically by the AWS web console when uploading large templates but unsure of the bucket name format.

**Comment by rbagai** [comment]
Is this feature available in cloudformation dsl ?
