### ISSUE TITLE
'require': cannot load such file -- cloudformation-ruby-dsl/cfntemplate (LoadError)

### ISSUE THREAD

**Issue by mhalligan** [bazaarvoice/cloudformation-ruby-dsl#32]
I'm having a problem loading the CFN gem. The only way I can use it is if I run it from a working directory which contains the cloudformation-ruby-dsl git repo. Otherwise I get the above error.

**Comment by jimcroft** [comment]
Sounds like your don't have the gem installed, just have a cloned repo. To fix either:

1. Install gem like any other
gem install cloudformation-ruby-dsl

or

2. Build and install gem from cloned repo
gem build cloudformation-ruby-dsl.gemspec
gem install cloudformation-ruby-dsl-0.4.10.gem

**Comment by temujin9** [comment]
@jimcroft has the correct answer. Thanks, Jim.

**Comment by mhalligan** [comment]
Thank you for your help, but I've done all 3 of those and no matter what I get the same issue. I've tested this on both Linux and OS X, different versions of ruby, etc.

**Comment by mhalligan** [comment]
this seemed to get fixed with the latest version, but the previous two were somehow hosed.

**Comment by SydOps** [comment]
seems the problem is back

```
$ cfntemplate-to-ruby test.json > test.rb
$ chmod +x test.rb

$ ./test.rb
./test.rb:4:in `require': cannot load such file -- cloudformation-ruby-dsl/cfntemplate (LoadError)
	from ./test.rb:4:in `<main>'
```

**Comment by temujin9** [comment]
You need the "require 'bundler/setup'" line at the top of your script. See https://github.com/bazaarvoice/cloudformation-ruby-dsl/blob/master/examples/simple_template.rb#L2 for an example. (This does the same thing as prepending the 'bundle exec'.)
