### ISSUE TITLE
CSV parse_char issue

### ISSUE THREAD

**Issue by zhelyan** [bazaarvoice/cloudformation-ruby-dsl#33]
`cfn-update-stack` fails because the CSV parser splits comma separated parameter values into different fields if the parameter string is double quoted. This , I believe, happens because of the change in 6ead33cd5d8b778a6f9f207445e31c28664fbd43. The actual error is: `cfn-update-stack may not update immutable parameter` and that's because the retrieved template parameters are never parsed beyond the parameter at which the split error occurs.

To reproduce: create a stack with description like "Stack, the" or one having a parameter which is a comma separated list and run `cfn-update-stack on it`

**Comment by temujin9** [comment]
Ah, dammit. Okay, use 0.4.10 while I devise a work-around.

**Comment by temujin9** [comment]
@zhelyan Please try 0.4.12; I've switched to XML parsing, which *should* avoid the buggy CSV in cfn-describe-stacks command.
