### ISSUE TITLE
service binary interferes with service command

### ISSUE THREAD

**Issue by aquach** [bazaarvoice/cloudformation-ruby-dsl#38]
Because the gem comes with a command called `service`, I can no longer use the usual `service` command on Ubuntu Linux without using its full path, since `service` now resolves to the gem's command rather than to the default, which manages starting or stopping services. Is there a way this command could be renamed to something less generic, or is there a way to selectively ignore commands or otherwise resolve this conflict so that I can use the gem? Right now all I can do is `rm` the `service` command out of `/usr/local/bin`. Thanks!

**Comment by temujin9** [comment]
Boo. Yeah, that's not good; I currently avoid it by [installing this DSL via Bundler](https://github.com/bazaarvoice/cloudformation-ruby-dsl#installation), and then [forcing the script into a bundler environment](https://github.com/bazaarvoice/cloudformation-ruby-dsl/blob/master/examples/cloudformation-ruby-script.rb#L17) prior to requiring the DSL. But we should either fix the underlying bug, or remove the instructions causing it from the README (and explain why we only do it via Bundler.

**Comment by temujin9** [comment]
Okay, version 0.5.0 and beyond should be clear of this bug. You may have to `gem uninstall cloudformation-ruby-dsl` to clean out the prior bad versions.

**Comment by aquach** [comment]
Thanks! Yeah, I thought installing via Bundler would namespace the gem such that I'd need to `bundle exec` to see the executable, but it didn't seem to work for me and I don't understand Bundler too well. Thanks for the fix!
