### ISSUE TITLE
Suggestion: Better name

### ISSUE THREAD

**Issue by jdrago999** [bazaarvoice/cloudformation-ruby-dsl#48]
This is Ruby.  While "cloudformation-ruby-dsl" is informative, it lacks a certain panache that all the other cool Ruby library names have.

I have no suggestions for any specific "better name" but I'd like to see such a great tool have an equally great name.

Also, cloudformation-ruby-dsl has saved me countless hours and has made it much easier to manage and grok otherwise complicated CloudFormation JSON templates.  Thank you!

**Comment by temujin9** [comment]
I appreciate it, but I think we're stuck with this name. Cool names have a way of obfuscating intent (one of my frustrations with the Ruby world, TBH), and we've already got a very broad internal install base who would be resistant to this change without a strong reason.

Glad you like the tool!
