### ISSUE TITLE
Testbed needed!

### ISSUE THREAD

**Issue by jonaf** [bazaarvoice/cloudformation-ruby-dsl#55]
Really, this should have been done when we first created the DSL, but we need to go ahead and put together a test suite to improve our releases and minimize breakage. There are quite a few edge cases and it gets quite complicated to test each change thoroughly.

**Comment by lwoodson** [comment]
Have added this PR https://github.com/bazaarvoice/cloudformation-ruby-dsl/pull/95

**Comment by temujin9** [comment]
It looks like @lwoodson has taken care of the basic framework for this.
