### ISSUE TITLE
Keyword arguments do not work in Ruby 1.9

### ISSUE THREAD

**Issue by oshmyrko** [bazaarvoice/cloudformation-ruby-dsl#59]
In [this commit](https://github.com/bazaarvoice/cloudformation-ruby-dsl/commit/a86e8b1354bae287e8b79ba6aa723e03fc6bbb33#diff-fdc133b99327fd40129c898b7cdf8395) you've added new method and variable with keyword argument:
```
  def initialize(**args)
    Aws.config[:region] = args[:region] if args.key?(:region)
  end

  aws_cfn = AwsCfn.new(region: template.aws_region)
```
but **keyword arguments** work only with **Ruby 2.0**.
Does it mean that we should use _cloudformation-ruby-dsl_ with _Ruby 2.0_ or it's just a mistake?

Thanks!

**Comment by jonaf** [comment]
Hi @oshmyrko , good find! Looks like we either need to stop supporting Ruby 1.9 or require Ruby 2.0. I guess we should fix this to support Ruby 1.9. @temujin9 Any thoughts/preference on this? I don't think there's anything else that is incompatible with Ruby 1.9 ...

**Comment by temujin9** [comment]
Let's keep Ruby 1.9 compatibility, at least for as long as it's simple to do so.

**Comment by jonaf** [comment]
Created #61 for this issue. @temujin9 care to take a quick look for me? Thanks.

**Comment by oshmyrko** [comment]
Hi @jonaf,
I'm not well familiar with Ruby, but I have one more question.
Should this line also be changed - [validate_params: false](https://github.com/bazaarvoice/cloudformation-ruby-dsl/blob/jfenocchi-ruby193/lib/cloudformation-ruby-dsl/cfntemplate.rb#L47)?
Seems this error is caused by that line:
```
/var/lib/gems/1.9.1/gems/cloudformation-ruby-dsl-1.0.3/lib/cloudformation-ruby-dsl/cfntemplate.rb:52: syntax error, unexpected keyword_end, expecting $end
	from ./logstash.rb:4:in `<main>'
```
Thanks!

**Comment by jonaf** [comment]
@oshmyrko I didn't get this error in Ruby 1.9.3-p551_1. What version of Ruby are you running? This error is due to the trailing comma, which is a preferred code style and acceptable in most places in most versions of Ruby (apparently, 1.9.1 doesn't like the trailing comma in method parameters?).

**Comment by oshmyrko** [comment]
I'm using Ruby 1.9.3p484:
```
$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

$ gem which cloudformation-ruby-dsl
/var/lib/gems/1.9.1/gems/cloudformation-ruby-dsl-1.0.3/lib/cloudformation-ruby-dsl.rb
```

**Comment by jonaf** [comment]
That's odd ... Why does `gem` indicate you have `cloudformation-ruby-dsl` installed for ruby 1.9.1, but your version of Ruby is 1.9.3?

**Comment by oshmyrko** [comment]
Found this - [Why are we installing Ruby 1.9.2/1.9.3 gems into a 1.9.1 folder?](http://stackoverflow.com/questions/8564210/why-are-we-installing-ruby-1-9-2-1-9-3-gems-into-a-1-9-1-folder), and [this](http://stackoverflow.com/questions/6352262/why-are-gems-installed-in-a-1-9-1-directory-when-my-ruby-version-is-different-th).
```
In Ruby 1.9.0, the C interface was changed from the Ruby 1.8 series.
Gems that compile to native code had to be recompiled.
The interface was again changed in Ruby 1.9.1 and kept the same in Ruby 1.9.2 & 3. This explains the 1.9.1 you are seeing in your path.
```
Seems it is normal.

**Comment by oshmyrko** [comment]
Thank you @jonaf,
it is working now.
