### ISSUE TITLE
Add --help option

### ISSUE THREAD

**Issue by jonaf** [bazaarvoice/cloudformation-ruby-dsl#69]
We need `--help`! Our documentation doesn't do a good job of providing usage info, and in general, we should be able to add `--help` to a command and get some usage instructions. This should alleviate some of the confusion / issues we have seen, such as #67 .

**Comment by SydOps** [comment]
Thanks, @jonaf

**Comment by bkruger99** [comment]
#92 

Hopefully this alleviates some of it.

**Comment by temujin9** [comment]
Closed via #92
