### ISSUE TITLE
Feature Idea: Templatized Interpolation of Init Scripts

### ISSUE THREAD

**Issue by johnlabarge** [bazaarvoice/cloudformation-ruby-dsl#70]
Apply a template (ERB) to the bash script erb before embedding it.   Add a context file as a parameter that the bash template uses it could have have things like an s3 bucket name/key and other server destinations etc.

**Comment by jonaf** [comment]
Hi @johnlabarge , currently the way we do this is via interpolation that happens within the bash script. You can use all the same references available in the scope of your template, wrapped in double curly braces (`{{` and `}}`) to interpolate those values into your userdata script. See the `interpolate` method described here:  https://github.com/bazaarvoice/cloudformation-ruby-dsl#utility-functions

Does this cover your needs, or did you have a different use-case in mind?

**Comment by temujin9** [comment]
Looks like this has been answered sufficiently; closing it.
