### ISSUE TITLE
Can I reference a parameter/tag/value inside a description?

### ISSUE THREAD

**Issue by digitaljedi2** [bazaarvoice/cloudformation-ruby-dsl#73]
I'd like to be able to define resources with dynamic descriptions such as:

 `resource 'DBSubnet', :Type => 'AWS::RDS::DBSubnetGroup', :Properties => {
    :DBSubnetGroupDescription => 'DBSubnet for #{ref(mystack)}'
    :CidrBlock => '10.0.201.0/24'
    :VpcId  => 'vpc123'`

**Comment by temujin9** [comment]
`ref()` simply expands to the JSON notation for a Cloudformation ref, which won't work inside a string. You can use `stack_name`, which should work for what you're trying here, provided it's properly quoted to allow interpolation (double quotes, not single quotes).

**Comment by digitaljedi2** [comment]
Thanks!
