### ISSUE TITLE
How to use tags?

### ISSUE THREAD

**Issue by digitaljedi2** [bazaarvoice/cloudformation-ruby-dsl#74]
I'm not sure how to use the tag capabilities in the DSL...
By the example below I was hoping to see all the resources created to have both tags Foo and Bar...
Is this incorrect? 
 `
 # Tags
  tag :Foo => ref('Foo')
  tag :Bar => ref('Bar')

  # Resources
  resource "vpc",
    :Type => 'AWS::EC2::VPC',
    :Properties => {
      :CidrBlock => '10.0.0.0/16',
      :InstanceTenancy => 'default',
      :EnableDnsSupport => 'true',
      :EnableDnsHostnames => 'true',
    }`

**Comment by temujin9** [comment]
The `tag` will set tags on the Cloudformation stack itself, which *should* set then those tags on resources created within that stack. That latter step is up to AWS' servers, not our code, and has historically lacked some coverage on underlying services.

**Comment by digitaljedi2** [comment]
Thanks again...
