### ISSUE TITLE
Suggestion: add get_output function

### ISSUE THREAD

**Issue by zhelyan** [bazaarvoice/cloudformation-ruby-dsl#82]
It will be handy if we can do e.g:

```ruby
  parameter 'VpcId',
            Type: 'String',
            Default: get_output('VpcId', 'my_vpc_template'),
            Description: 'The ID of you Virtual Private Cloud (VPC)',
            Immutable: true
```

**Comment by jonaf** [comment]
Hi @zhelyan , you can already do this if your Cloudformation stack creates stacks, but they all have to be in the same template. See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html

> You can add output values from a nested stack within the containing template. You use the GetAtt function with the nested stack's logical name and the name of the output value in the nested stack in the format Outputs.NestedStackOutputName.

Alternatively, if you didn't create your other stack in the same template, it should be pretty straightforward to implement this yourself. I think our hesitation with adding something like this would be along the lines of...there are so many ways you could get data into your template, and the ruby dsl doesn't really have any opinion on *how* you do it. You could read it from a file (we do provide general support for reading in from file tables), you could pass it in on the command line and have something else interpolate it before it gets to the dsl, or you could even write your own little method inside your template (remember, it's all Ruby!) to perform whatever task you like.

Is there anything special about this particular functionality that would make your life easier on a regular basis or for multiple projects? I'm totally wiling to recant my opinion if this gets some +1's from the community.

**Comment by zhelyan** [comment]
It is a great library and you are right, it shouldn't try to solve    every problem. On a second thought my issue is more or less as explained in #57 so you can close this one as it isn't really a deal breaker.

**Comment by jonaf** [comment]
Okay, I'll close this for now. We can re-open it later if we decide it deserves first-class support. Cheers!
